// This file is auto-generated by KSP. Do not edit manually.
import Composables
import Models
import SwiftUI

public struct GradientScreenMixedARepresentable: UIViewControllerRepresentable {
    @Binding public var state: ScreenState
    public let randomize: (Int64) -> Void
    public init(state: Binding<ScreenState>, randomize: @escaping (Int64) -> Void) {
        _state = state
        self.randomize = randomize
    }

    public func makeUIViewController(context _: Context) -> UIViewController {
        GradientScreenMixedAUIViewController.shared.make(randomize: randomize)
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        GradientScreenMixedAUIViewController.shared.update(state: state)
    }
}
