// This file is auto-generated by KSP. Do not edit manually.
import Composables
import SwiftUI

public struct GradientScreenMixedBRepresentable: UIViewControllerRepresentable {
    @Binding var state: ScreenState
    let controller: UIViewController

    public func makeUIViewController(context _: Context) -> UIViewController {
        GradientScreenMixedBUIViewController().make(controller: controller)
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        GradientScreenMixedBUIViewController().update(state: state)
    }
}
