// This file is auto-generated by KSP. Do not edit manually.
import SwiftUI
import SharedModels
import Composables

public struct GradientScreenRepresentable: UIViewControllerRepresentable {
    @Binding var state: ScreenStateExternal
    let randomize: (Int64) -> Void

    public func makeUIViewController(context: Context) -> UIViewController {
        GradientScreenUIViewController.shared.make(randomize: randomize)
    }

    public func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
        GradientScreenUIViewController.shared.update(state: state)
    }
}