// This file is auto-generated by KSP. Do not edit manually.
import Composables
import SwiftUI

public struct GradientScreenMixedARepresentable: UIViewControllerRepresentable {
    @Binding var state: ScreenState
    let randomize: (KotlinLong) -> Void

    public func makeUIViewController(context _: Context) -> UIViewController {
        GradientScreenMixedAUIViewController().make(randomize: randomize)
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        GradientScreenMixedAUIViewController().update(state: state)
    }
}
