// This file is auto-generated by KSP. Do not edit manually.
import Composables
import SwiftUI

public struct GradientScreenSwiftRepresentable: UIViewControllerRepresentable {
    let controller: UIViewController

    public func makeUIViewController(context _: Context) -> UIViewController {
        GradientScreenSwiftUIViewController().make(controller: controller)
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        // unused
    }
}
