// This file is auto-generated by KSP. Do not edit manually.
import Composables
import SwiftUI

public struct GradientScreenComposeRepresentable: UIViewControllerRepresentable {
    @Binding var state: ScreenState
    let randomize: (KotlinLong) -> Void

    public func makeUIViewController(context _: Context) -> UIViewController {
        GradientScreenComposeUIViewController().make(randomize: randomize)
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        GradientScreenComposeUIViewController().update(state: state)
    }
}
