// This file is auto-generated by KSP. Do not edit manually.
import Composables
import Models
import SwiftUI

public struct GradientScreenMixedARepresentable: UIViewControllerRepresentable {
    @Binding var state: ScreenState
    let randomize: (Int64) -> Void

    public func makeUIViewController(context _: Context) -> UIViewController {
        GradientScreenMixedAUIViewController.shared.make(randomize: randomize)
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        GradientScreenMixedAUIViewController.shared.update(state: state)
    }
}
