// swift-tools-version: 5.9
// Auto-generated by KMP-ComposeUIViewController — do not edit manually.

import PackageDescription

let package = Package(
    name: "Representables",
    products: [
        .library(name: "Representables", targets: ["Representables"])
    ],
    dependencies: [
        .package(path: "../../shared/build/SPMPackage/Composables")
    ],
    targets: [
        .target(
            name: "Representables",
            dependencies: [
                .product(name: "ComposablesLibrary", package: "Composables")
            ],
            path: "Sources/Representables"
        )
    ]
)
