// swift-tools-version: 6.2
// Auto-generated by KMP-ComposeUIViewController — do not edit manually.

import PackageDescription

let package = Package(
    name: "Representables",
    platforms: [
        .iOS(.v26)
    ],
    products: [
        .library(name: "Representables", targets: ["Representables"])
    ],
    targets: [
        .target(
            name: "Representables",
            path: "Sources/Representables",
            swiftSettings: [
                .unsafeFlags(["-I", "../../shared/build/SPMBuild/SwiftInterfaces", "-I", "../../shared/build/SPMPackage/OtherIncludes/KotlinCoroutineSupportBridge", "-I", "../../shared/build/SPMPackage/OtherIncludes/KotlinRuntime", "-I", "../../shared/build/SPMPackage/OtherIncludes/KotlinRuntimeSupportBridge", "-I", "../../shared/build/SPMPackage/OtherIncludes/SharedBridge_Composables", "-I", "../../shared/build/SPMPackage/OtherIncludes/SharedBridge_Models"])
            ]
        )
    ]
)
