// This file is auto-generated by KSP. Do not edit manually.
import SwiftUI
import Composables

public struct TestRepresentable: UIViewControllerRepresentable {
    let v1: KotlinBoolean
    let v2: (KotlinBoolean) -> Void

    public func makeUIViewController(context: Context) -> UIViewController {
        TestUIViewController().make(v1: v1, v2: v2)
    }

    public func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
        //unused
    }
}