// This file is auto-generated by KSP. Do not edit manually.
import Composables
import SwiftUI

public struct TestRepresentable: UIViewControllerRepresentable {
    let callBackA: () -> Void
    let callBackB: ([[String: [KotlinInt]]]) -> [String]
    let callBackS: (Set<KotlinInt>) -> Void
    let callBackC: (NSMutableArray) -> Void
    let callBackD: ([String: String]) -> Void
    let callBackE: (NSMutableDictionary) -> Void
    let callBackF: (KotlinByte) -> Void
    let callBackG: (KotlinUByte) -> Void
    let callBackH: (KotlinShort) -> Void
    let callBackI: (KotlinUShort) -> Void
    let callBackJ: (KotlinInt) -> Void
    let callBackK: (KotlinUInt) -> Void
    let callBackL: (KotlinLong) -> Void
    let callBackM: (KotlinULong) -> Void
    let callBackN: (KotlinFloat) -> Void
    let callBackO: (KotlinDouble) -> Void
    let callBackP: (KotlinBoolean) -> Void

    public func makeUIViewController(context _: Context) -> UIViewController {
        TestUIViewController().make(callBackA: callBackA, callBackB: callBackB, callBackS: callBackS, callBackC: callBackC, callBackD: callBackD, callBackE: callBackE, callBackF: callBackF, callBackG: callBackG, callBackH: callBackH, callBackI: callBackI, callBackJ: callBackJ, callBackK: callBackK, callBackL: callBackL, callBackM: callBackM, callBackN: callBackN, callBackO: callBackO, callBackP: callBackP)
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        // unused
    }
}
