package com.github.guilhe.kmp.composeuiviewcontroller.gradle

internal fun stubPackageSwift(packageName: String): String =
	"""
// swift-tools-version: 5.9
// Auto-generated by KMP-ComposeUIViewController — do not edit manually.
// Stub: build the project once in Xcode to activate the full Swift Export dependency.

import PackageDescription

let package = Package(
    name: "$packageName",
    products: [
        .library(name: "$packageName", targets: ["$packageName"])
    ],
    targets: [
        .target(
            name: "$packageName",
            path: "Sources/$packageName"
        )
    ]
)
""".trimIndent()

internal const val VERSION_LIBRARY = "2.4.0-1.11.1"
internal const val LOG_TAG = "KmpComposeUIViewControllerPlugin"
internal const val PLUGIN_KMP = "org.jetbrains.kotlin.multiplatform"
internal const val PLUGIN_KSP = "com.google.devtools.ksp"
internal const val LIB_GROUP = "com.github.guilhe.kmp"
internal const val LIB_KSP_NAME = "kmp-composeuiviewcontroller-ksp"
internal const val LIB_KSP = "$LIB_GROUP:$LIB_KSP_NAME:$VERSION_LIBRARY"
internal const val LIB_ANNOTATIONS_NAME = "kmp-composeuiviewcontroller-annotations"
internal const val LIB_ANNOTATION = "$LIB_GROUP:$LIB_ANNOTATIONS_NAME:$VERSION_LIBRARY"
internal const val EXTENSION_PLUGIN = "ComposeUiViewController"
internal const val TASK_CLEAN_TEMP_FILES_FOLDER = "cleanTempFilesFolder"
internal const val TASK_COPY_FILES_TO_XCODE = "copyFilesToXcode"
internal const val TASK_EXPORT_TO_SPM = "exportToSpm"
internal const val TASK_SETUP_SPM_PACKAGE = "createRepresentablesPackage"
internal const val TASK_DELETE_SPM_PACKAGE = "deleteRepresentablesPackage"
internal const val TASK_FORMAT_SWIFT_FILES = "formatSwiftFiles"
internal const val TASK_VALIDATE_REPRESENTABLES = "validateRepresentables"
internal const val TASK_EMBED_AND_SING_APPLE_FRAMEWORK_FOR_XCODE = "embedAndSignAppleFrameworkForXcode"
internal const val TASK_EMBED_SWIFT_EXPORT_FOR_XCODE = "embedSwiftExportForXcode"
internal const val TASK_SYNC_FRAMEWORK = "syncFramework"
internal const val FILE_NAME_SETUP_SPM_SCRIPT = "createRepresentablesPackage.sh"
internal const val FILE_NAME_DELETE_SPM_SCRIPT = "deleteRepresentablesPackage.sh"
internal const val FILE_NAME_SPM_SCRIPT = "exportToSpm.sh"
internal const val FILE_NAME_COPY_SCRIPT = "exportToXcode.sh"
internal const val FILE_NAME_FORMAT_SCRIPT = "sformat.sh"
internal const val FILE_NAME_FORMAT_SCRIPT_TEMP = "temp_format.sh"
internal const val FILE_NAME_COPY_SCRIPT_TEMP = "temp.sh"
internal const val FILE_NAME_SPM_SCRIPT_TEMP = "temp_spm.sh"
internal const val FILE_NAME_SETUP_SPM_SCRIPT_TEMP = "temp_setup_spm.sh"
internal const val FILE_NAME_DELETE_SPM_SCRIPT_TEMP = "temp_delete_spm.sh"
internal const val PARAM_KEEP_FILE = "keepScriptFile"
internal const val PARAM_KMP_MODULE = "kmp_module"
internal const val PARAM_FOLDER = "iosApp_project_folder"
internal const val PARAM_APP_NAME = "iosApp_name"
internal const val PARAM_TARGET = "iosApp_target_name"
internal const val PARAM_GROUP = "group_name"
internal const val PARAM_SPM_MODULE = "spm_module_name"
internal const val PARAM_IOS_DEPLOYMENT_TARGET = "ios_deployment_target"
internal const val PARAM_SWIFT_TOOLS_VERSION = "swift_tools_version"
internal const val KSP_ARG_METADATA_HASH = "composeuiviewcontroller.metadataHash"
internal const val ERROR_MISSING_KMP = "$LOG_TAG requires the Kotlin Multiplatform plugin to be applied."
internal const val ERROR_MISSING_PACKAGE = "Could not determine project's package"
internal const val ERROR_MISSING_FRAMEWORK_CONFIG = "No framework configuration found."
internal const val ERROR_MISSING_FRAMEWORK_CONFIG_FULL =
	"$ERROR_MISSING_FRAMEWORK_CONFIG Please configure in the exporting module either:\n" +
		"\t1. iOS framework baseName, or\n" +
		"\t2. SwiftExport with moduleName"
internal const val INFO_MODULE_NAME_BY_FRAMEWORK =
	"SwiftExport is NOT configured, will use all iOS targets' framework baseName as frameworkBaseName:"
internal const val INFO_MODULE_NAME_BY_SWIFT_EXPORT = "SwiftExport is configured, will use its moduleName:"