#!/bin/bash

# DEFAULT VALUES
iosApp_project_folder="iosApp"
iosApp_name="iosApp"
iosApp_target_name="iosApp"
group_name="Representables"
swift_tools_version="6.2"
#####################

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/../../" && pwd )"
IOS_APP_DIR="$PROJECT_ROOT/$iosApp_project_folder"

spm_package_dir="$iosApp_project_folder/$group_name"
sources_dir="$spm_package_dir/Sources/$group_name"
xcodeproj_path="$iosApp_name.xcodeproj"

install_gem() {
  local gem_name="$1"
  local version_constraint="$2"
  local install_output
  install_output=$(gem install "$gem_name" -v "$version_constraint" 2>&1)
  if [ $? -ne 0 ]; then
    if echo "$install_output" | grep -q "FilePermissionError\|don't have write permissions"; then
      echo "  > Permission denied. Installing to user directory..."
      install_output=$(gem install "$gem_name" -v "$version_constraint" --user-install 2>&1)
      if [ $? -eq 0 ]; then
        local user_gem_bin
        user_gem_bin="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin"
        if [ -d "$user_gem_bin" ] && [[ ":$PATH:" != *":$user_gem_bin:"* ]]; then
          export PATH="$user_gem_bin:$PATH"
        fi
      else
        echo "  > ERROR: Failed to install gem even with --user-install"
        echo "$install_output"
        exit 1
      fi
    else
      echo "  > ERROR: Failed to install gem"
      echo "$install_output"
      exit 1
    fi
  fi
}

check_for_xcodeproj() {
  local min_version="1.27.0"
  local current_version
  current_version=$(gem list xcodeproj --local 2>/dev/null | grep "^xcodeproj " | sed 's/.*(\([0-9.]*\).*/\1/')
  if [ -z "$current_version" ]; then
    echo "  > Installing xcodeproj gem (minimum version: $min_version)..."
    install_gem "xcodeproj" ">= $min_version"
  else
    if [ "$(printf '%s\n' "$min_version" "$current_version" | sort -V | head -n1)" != "$min_version" ]; then
      echo "  > Updating xcodeproj gem to >= $min_version..."
      install_gem "xcodeproj" ">= $min_version"
    else
      echo "  > Using xcodeproj gem version $current_version"
    fi
  fi
  if ! gem spec xcodeproj > /dev/null 2>&1; then
    echo "  > ERROR: Failed to verify xcodeproj gem"
    exit 1
  fi
}

generate_stub_package_swift() {
  cat << SWIFT_EOF
// swift-tools-version: $swift_tools_version
// Auto-generated by KMP-ComposeUIViewController — do not edit manually.
// Stub: build the project once in Xcode to activate the full Swift Export dependency.

import PackageDescription

let package = Package(
    name: "$group_name",
    products: [
        .library(name: "$group_name", targets: ["$group_name"])
    ],
    targets: [
        .target(
            name: "$group_name",
            path: "Sources/$group_name"
        )
    ]
)
SWIFT_EOF
}

create_spm_package_stub() {
  mkdir -p "$sources_dir"

  # SPM requires at least one source file per target. The placeholder is kept permanently
  # alongside the real generated files to avoid Xcode "Build input file cannot be found" errors.
  # populates Sources/ with the real KSP-generated files.
  local placeholder="$sources_dir/Placeholder.swift"
  if [ ! -f "$placeholder" ]; then
    printf '// This file is intentionally kept by KMP-ComposeUIViewController.\n// It prevents the SPM "target is empty" error when Sources/ has no generated files yet.\n' > "$placeholder"
  fi

  local package_swift="$spm_package_dir/Package.swift"
  local new_content
  new_content=$(generate_stub_package_swift)

  if [ -f "$package_swift" ]; then
    local existing_content
    existing_content=$(cat "$package_swift")
    if [ "$new_content" = "$existing_content" ]; then
      echo "  > Package.swift stub is already up to date"
      return 0
    fi
    echo "  > Package.swift reset to stub"
  else
    echo "  > Package.swift stub created"
  fi

  printf '%s\n' "$new_content" > "$package_swift"
}

add_to_xcodeproj() {
  ruby_script='
    require "xcodeproj"

    xcodeproj_path  = ARGV[0]
    target_name     = ARGV[1]
    relative_path   = ARGV[2]
    product_name    = ARGV[3]

    begin
      project = Xcodeproj::Project.open(xcodeproj_path)
    rescue => e
      puts "  > ERROR: Failed to open Xcode project: #{e.message}"
      exit 1
    end

    target = project.targets.find { |t| t.name == target_name }
    unless target
      puts "  > ERROR: Target \"#{target_name}\" not found in project"
      exit 1
    end

    existing_refs = project.root_object.package_references.to_a rescue []
    already_added = existing_refs.any? do |ref|
      ref.isa == "XCLocalSwiftPackageReference" &&
        ref.respond_to?(:relative_path) &&
        ref.relative_path == relative_path
    end

    if already_added
      puts "  > Package \"#{product_name}\" already added to project. Skipping"
      exit 0
    end

    pkg_ref = project.new(Xcodeproj::Project::Object::XCLocalSwiftPackageReference)
    pkg_ref.relative_path = relative_path
    project.root_object.package_references << pkg_ref

    pkg_dep = project.new(Xcodeproj::Project::Object::XCSwiftPackageProductDependency)
    pkg_dep.package = pkg_ref
    pkg_dep.product_name = product_name
    target.package_product_dependencies << pkg_dep

    begin
      project.save
      puts "  > Added \"#{product_name}\" local package to target \"#{target_name}\""
    rescue => e
      puts "  > ERROR: Failed to save Xcode project: #{e.message}"
      exit 1
    end
  '
  ruby -e "$ruby_script" "$xcodeproj_path" "$iosApp_target_name" "$group_name" "$group_name"
}

echo "  > Creating SPM package stub..."
create_spm_package_stub

echo "  > Adding package reference to Xcode project..."
check_for_xcodeproj
cd "$IOS_APP_DIR" || exit
add_to_xcodeproj

echo ""
echo "  > Setup complete."
echo "  > Build the project once in Xcode — the full Swift Export dependency will be activated automatically."