// This file is auto-generated by KSP. Do not edit manually.
import Composables
import SwiftUI

public struct GradientScreenMixedARepresentable: UIViewControllerRepresentable {
    @Binding public var state: ScreenState
    public let randomize: (KotlinLong) -> Void

    public init(state: Binding<ScreenState>, randomize: @escaping (KotlinLong) -> Void) {
        _state = state
        self.randomize = randomize
    }

    public func makeUIViewController(context _: Context) -> UIViewController {
        GradientScreenMixedAUIViewController().make(randomize: randomize)
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        GradientScreenMixedAUIViewController().update(state: state)
    }
}
