// This file is auto-generated by KSP. Do not edit manually.
import Composables
import SwiftUI

public struct GradientScreenMixedBRepresentable: UIViewControllerRepresentable {
    @Binding public var state: ScreenState
    public let controller: UIViewController
    public init(state: Binding<ScreenState>, controller: UIViewController) {
        _state = state
        self.controller = controller
    }

    public func makeUIViewController(context _: Context) -> UIViewController {
        GradientScreenMixedBUIViewController().make(controller: controller)
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        GradientScreenMixedBUIViewController().update(state: state)
    }
}
