// swift-tools-version: 6.2
// Auto-generated by KMP-ComposeUIViewController — do not edit manually.

import PackageDescription

let package = Package(
    name: "Representables",
    platforms: [
        .iOS(.v26)
    ],
    products: [
        .library(name: "Representables", targets: ["Representables"])
    ],
    targets: [
        .target(
            name: "Representables",
            path: "Sources/Representables",
            swiftSettings: [
                .unsafeFlags(["-F", "../../shared/build/xcode-frameworks/current"])
            ],
            linkerSettings: [
                .unsafeFlags(["-F", "../../shared/build/xcode-frameworks/current", "-framework", "Composables"])
            ]
        )
    ]
)
