// swift-tools-version: 5.9
// Auto-generated by KMP-ComposeUIViewController — do not edit manually.
// Stub: build the project once in Xcode to activate the full Swift Export dependency.

import PackageDescription

let package = Package(
    name: "Representables",
    products: [
        .library(name: "Representables", targets: ["Representables"])
    ],
    targets: [
        .target(
            name: "Representables",
            path: "Sources/Representables"
        )
    ]
)