// This file is auto-generated by KSP. Do not edit manually.
import Composables
import SwiftUI

public struct GradientScreenComposeRepresentable: UIViewControllerRepresentable {
    public init() {}

    public func makeUIViewController(context _: Context) -> UIViewController {
        GradientScreenComposeUIViewController.shared.make()
    }

    public func updateUIViewController(_: UIViewController, context _: Context) {
        // unused
    }
}
